services:
  build:
    image: node:24-alpine
    working_dir: /app
    volumes:
      - .:/app
    command: sh -c "npm install && npm run build"
  nginx:
    build:
      context: .
      dockerfile: Dockerfile
      target: production-stage
    ports:
      - '80:80'
    depends_on:
      - build
